### PR TITLE
use graphql-tools-fork

### PR DESCRIPTION
**Pull request by yaacovCR**
Required fix released in graphql-tools-fork v8.5.2

### CODE REVIEW

**Comment by yaacovCR** [comment]
Although I believe the fork requires at least graphql v14.2 and upstream graphql-tools and presumably @ardatan/graphql-tools requires graphql at least v14, so I am not sure whether the peerDepedency version on graphql should be changed as well.

**Comment by ardatan** [comment]
I need to trigger CI for this PR to make sure tests pass for both v14 and v15.

**Comment by ardatan** [comment]
@yaacovCR Could you update your PR with latest changes because I fixed something related to CI? I want to see if this PR works with v15 because I don't think it does.

**Comment by yaacovCR** [comment]
graphql-tools-fork requires graphql v14.2 and above as it relies heavily on toConfig -- I took the liberty of making the same change in this PR across the board in graphql-toolkit.

**Comment by yaacovCR** [comment]
@ardatan thoughts?

**Comment by yaacovCR** [comment]
graphql-tools-fork v8.6.2 is tested with graphql v0.12 and above.

The fork may or may not work with v0.9-v0.11.

I am not sure if the upstream graphql-tools works from v0.9-0.11. Currently, the upstream repository tests fail on upstream graphql-tools for anything below v0.13. For the fork, I fixed the tests for v0.12 by adding the necessary polyfills, as that is what Apollo Server apparently supports (see https://github.com/apollographql/graphql-tools/pull/1284), but did not go back further.

**Comment by yaacovCR** [comment]
@ardatan I removed changes to peerDependency requirement, but I have not confirmed the status of this repository, upstream graphql-tools, or graphql-tools-fork with graphql v0.8-v0.11

**Comment by darkbasic** [comment]
I support this: the official graphql-tools library is broken in so many ways, sometimes completely unrelated to schema stitching. It's not even possible to follow the official Apollo docs without unveiling some nasty bugs: https://github.com/apollographql/graphql-tools/issues/1265

**Comment by ardatan** [comment]
Thank you @yaacovCR !

**Pull request merged**
